In [30]:
import pandas as pd
from pandas import DataFrame
from pylab import *
import matplotlib.pyplot as plot
import seaborn as sns
import dateutil
import plotly
import plotly.graph_objs as go

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot


# plot([go.Scatter(x=[1, 2, 3], y=[3, 1, 6])])


# print plotly.__version__

perfdata=pd.read_csv("/Users/abayomi/Downloads/data.csv")
# data = pd.DataFrame.from_csv('phone_data.csv')

print perfdata.head()

date_count = perfdata[['Intent_Date','Intent_Completed_Count']]

region_count = perfdata[['Merchant_Region_Name','Intent_Completed_Count']]

# print region_count.head()
# print date_count.head()

# print perfdata[perfdata['Merchant_Region_Name'] == 'ASIAPAC'].sum()
# print perfdata.groupby(['Merchant_Region_Name']).groups.keys()

print 

# print perfdata.groupby(['Merchant_Region_Name'])['Intent_Completed_Count'].count()

print 

groupbyRegion = perfdata['Intent_Completed_Count'].groupby(perfdata['Merchant_Region_Name'])

groupbyRegion2 =  perfdata.groupby('Merchant_Region_Name').describe()
groupbyRegion2 


regions = []

counts_data = []
counts_mean = []


# print groupbyRegion.describe()




# groupbyRegion.boxplot(by = 'Merchant_Region_Name' )

# groupbyRegion.iplot(kind='box', filename='cufflinks/box-plots')

  Intent_Date Merchant_Region_Name  Intent_Completed_Count
0   10/1/2015              ASIAPAC                    2406
1   10/1/2015           C.E.M.E.A.                     146
2   10/1/2015               CANADA                    2660
3   10/1/2015               U.S.A.                   25077
4   10/2/2015              ASIAPAC                    2436

                     Intent_Completed_Count                              \
                                      count          mean           std
Merchant_Region_Name
ASIAPAC                               976.0   5038.363730   2699.833159
C.E.M.E.A.                            976.0    750.336066    600.621548
CANADA                                976.0   3634.388320   2402.049313
EUROPE                                513.0  10983.649123  12651.922938
LAT.AM.                               962.0   4568.948025  10486.420718
U.S.A.                                976.0  52842.311475  28329.677695


                          min       25%      50%       75%       max
Merchant_Region_Name
ASIAPAC                1168.0   3308.75   5015.5   6050.75   41149.0
C.E.M.E.A.               13.0    215.00    677.0   1178.25    5847.0
CANADA                 1683.0   2604.75   3210.0   3859.00   45886.0
EUROPE                    0.0    231.00   1679.0  19790.00   59383.0
LAT.AM.                   0.0    257.50   2593.5   4828.00  126829.0
U.S.A.                21900.0  36106.00  46370.0  60859.75  376679.0